/**
 * Arbiter — collapses several engine responses into one answer.
 *
 * The output that matters most is `synopsis`: two or three sentences of plain
 * spoken English. It is the SMS body, the push notification, and the
 * text-to-speech input, and for most thoughts it is the only thing the user
 * ever reads. The full `synthesis` is there when they want to go deeper.
 */

import Anthropic from "@anthropic-ai/sdk";
import type { Engine } from "./config";
import { parseJsonLoose } from "./json";
import { getQueryFn, type ProviderResponse } from "./providers";

const LABELS = ["A", "B", "C", "D", "E", "F"] as const;
const REPAIR_MODEL = "claude-haiku-4-5-20251001";

let _repairClient: Anthropic | null = null;
function getRepairClient(): Anthropic {
  if (!_repairClient) _repairClient = new Anthropic();
  return _repairClient;
}

export interface Disagreement {
  topic: string;
  positions: Record<string, string>;
  assessment: string;
}

export interface ArbiterResult {
  synopsis: string;
  synthesis: string;
  bestLabel: string | null;
  bestEngine: Engine | null;
  bestRationale: string;
  disagreements: Disagreement[];
}

/* ── Prompt ──────────────────────────────────────────────────────────── */

const SYNOPSIS_SPEC = `"synopsis": Two to three sentences that answer the question directly. This is the single most important field. It will be sent as a text message and read aloud by a speech synthesiser, so:
  - Lead with the answer itself. Never open with restatement or preamble.
  - Plain prose only. No markdown, no bullet points, no headings, no bracketed citation numbers, no URLs.
  - Write it the way a well-informed friend would say it out loud.
  - Include the specific number, name, or date if there is one. Concrete beats hedged.
  - If the honest answer is genuinely uncertain or the sources conflict, say so plainly in one clause and then give the best available answer anyway. Do not refuse and do not pad with caveats.`;

function buildArbiterSystem(count: number): string {
  const labels = LABELS.slice(0, count);
  const labelList =
    count === 1
      ? "A"
      : `${labels.slice(0, -1).join(", ")}, and ${labels[labels.length - 1]}`;
  const labelUnion = labels.map((l) => `"${l}"`).join(" | ");
  const positionsExample = labels.map((l) => `"${l}": "..."`).join(", ");

  return `You are an impartial arbiter inside a personal question-answering system. You will receive ${count === 1 ? "one response" : `${count} responses`} to the same question, labelled ${labelList}. You do not know which AI produced which response. Evaluate purely on merit.

All responses were generated by models with LIVE WEB SEARCH access. Specific facts, figures, dates and prices in them come from searches performed moments ago. Treat that data as authoritative and current. Never add disclaimers about lacking real-time data or having a knowledge cutoff — the data in front of you IS current.

Return your analysis as JSON with exactly these keys:

{
  ${SYNOPSIS_SPEC}

  "synthesis": "The full answer in markdown. Incorporate the specific facts, figures and findings from the responses. Keep it as long as the question genuinely warrants and no longer. Do not describe the responses or the comparison process — write the answer itself, as though you had researched it directly.",

  "best": ${labelUnion},
  "best_rationale": "One or two sentences on why that response was strongest.",

  "disagreements": [
    {
      "topic": "What the responses actually disagree about",
      "positions": {${positionsExample}},
      "assessment": "Which position is most likely correct, and why."
    }
  ]
}

Only report a disagreement when the responses make genuinely incompatible claims about a fact or a recommendation. Differences of emphasis, wording, length or structure are not disagreements. Most questions have none, and an empty array is the correct and expected answer in that case.

Return ONLY valid JSON. No markdown fences, no commentary outside the JSON.`;
}

function buildArbiterPrompt(
  prompt: string,
  responses: ProviderResponse[]
): string {
  const sections = [`## Question\n\n${prompt}\n`];
  responses.forEach((r, i) => {
    sections.push(`## Response ${LABELS[i]}\n\n${r.text}\n`);
  });
  return sections.join("\n");
}

/* ── Main entry point ────────────────────────────────────────────────── */

interface ArbiterJson {
  synopsis?: string;
  synthesis?: string;
  best?: string;
  best_rationale?: string;
  disagreements?: Disagreement[];
}

export async function arbitrate(
  prompt: string,
  responses: ProviderResponse[],
  arbiterEngine: Engine
): Promise<ArbiterResult> {
  if (responses.length === 0) {
    throw new Error("Cannot arbitrate with no responses");
  }

  const queryFn = getQueryFn(arbiterEngine);
  const userPrompt = buildArbiterPrompt(prompt, responses);

  // Web search off: the arbiter's job is to judge what it was given and
  // return strict JSON, not to go looking for more.
  const arbiterResponse = await queryFn(userPrompt, "research", "research", {
    webSearch: false,
    systemOverride: buildArbiterSystem(responses.length),
  });

  let data = parseJsonLoose<ArbiterJson>(arbiterResponse.text);

  if (!data) data = await repairJson(arbiterResponse.text);

  // Still nothing usable — degrade rather than fail. A thought that reaches
  // the user as a plain best-response beats one stuck in 'synthesizing'.
  if (!data) return degradedResult(responses);

  const labelToEngine: Record<string, Engine> = {};
  responses.forEach((r, i) => {
    labelToEngine[LABELS[i]] = r.engine;
  });

  const bestLabel =
    typeof data.best === "string" && labelToEngine[data.best]
      ? data.best
      : null;

  const synthesis =
    typeof data.synthesis === "string" && data.synthesis.trim()
      ? data.synthesis.trim()
      : responses[0].text;

  const synopsis =
    typeof data.synopsis === "string" && data.synopsis.trim()
      ? data.synopsis.trim()
      : deriveSynopsis(synthesis);

  return {
    synopsis,
    synthesis,
    bestLabel,
    bestEngine: bestLabel ? labelToEngine[bestLabel] : null,
    bestRationale:
      typeof data.best_rationale === "string" ? data.best_rationale : "",
    disagreements: normaliseDisagreements(data.disagreements),
  };
}

/**
 * Single-engine path. Quick thoughts skip arbitration entirely — the response
 * is already one or two sentences, so it is its own synopsis.
 */
export function passThrough(response: ProviderResponse): ArbiterResult {
  const text = response.text.trim();
  return {
    synopsis: deriveSynopsis(text),
    synthesis: text,
    bestLabel: "A",
    bestEngine: response.engine,
    bestRationale: "",
    disagreements: [],
  };
}

/* ── Helpers ─────────────────────────────────────────────────────────── */

/** One cheap attempt to extract valid JSON from a chatty arbiter reply. */
async function repairJson(raw: string): Promise<ArbiterJson | null> {
  try {
    const response = await getRepairClient().messages.create({
      model: REPAIR_MODEL,
      max_tokens: 4000,
      system:
        "Extract the JSON object from the text you are given and return it, corrected so that it parses. Preserve every field value exactly as written. Return ONLY the JSON object — no fences, no commentary.",
      messages: [{ role: "user", content: raw.slice(0, 100_000) }],
    });

    const text = response.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("");

    return parseJsonLoose<ArbiterJson>(text);
  } catch {
    return null;
  }
}

/** Last resort: hand back the longest response rather than failing. */
function degradedResult(responses: ProviderResponse[]): ArbiterResult {
  const longest = responses.reduce((a, b) =>
    b.text.length > a.text.length ? b : a
  );
  const text = longest.text.trim();

  return {
    synopsis: deriveSynopsis(text),
    synthesis: text,
    bestLabel: null,
    bestEngine: longest.engine,
    bestRationale: "",
    disagreements: [],
  };
}

/**
 * Reduce markdown to something speakable. Used whenever the model did not
 * give us a usable synopsis of its own.
 */
export function deriveSynopsis(text: string, maxChars = 400): string {
  const plain = text
    // Drop an appended Sources block.
    .replace(/\n+#{0,3}\s*sources?:?[\s\S]*$/i, "")
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/^\s{0,3}#{1,6}\s+/gm, "")
    .replace(/^\s{0,3}[-*+]\s+/gm, "")
    .replace(/^\s{0,3}\d+\.\s+/gm, "")
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/\[\d+\]/g, "")
    .replace(/[*_`>]/g, "")
    .replace(/\s+/g, " ")
    .trim();

  if (plain.length <= maxChars) return plain;

  // Cut on a sentence boundary if there is a reasonable one.
  const window = plain.slice(0, maxChars);
  const lastStop = Math.max(
    window.lastIndexOf(". "),
    window.lastIndexOf("! "),
    window.lastIndexOf("? ")
  );
  if (lastStop > maxChars * 0.5) return window.slice(0, lastStop + 1).trim();

  return `${window.trim()}…`;
}

function normaliseDisagreements(input: unknown): Disagreement[] {
  if (!Array.isArray(input)) return [];

  return input.flatMap((d): Disagreement[] => {
    if (!d || typeof d !== "object") return [];
    const candidate = d as Partial<Disagreement>;
    if (typeof candidate.topic !== "string") return [];

    return [
      {
        topic: candidate.topic,
        positions:
          candidate.positions && typeof candidate.positions === "object"
            ? candidate.positions
            : {},
        assessment:
          typeof candidate.assessment === "string" ? candidate.assessment : "",
      },
    ];
  });
}
