/** Arbiter — sends all responses to a chosen engine for blind evaluation. */

import type { Engine } from "./config";
import { getQueryFn, type ProviderResponse } from "./providers";

const ALL_LABELS = ["A", "B", "C", "D", "E", "F"];
const MAX_ATTEMPTS = 2;

function buildSystemPrompt(labels: string[]): string {
  const list = labels.join(", ");
  const union = labels.map((l) => `"${l}"`).join(" | ");
  const positions = labels.map((l) => `"${l}": "..."`).join(", ");
  return `You are an impartial arbiter. You will receive ${labels.length} responses to the same user query, labelled ${list}. You do NOT know which AI produced which response — evaluate them purely on merit.

IMPORTANT: All responses were generated by AI models that had LIVE WEB SEARCH access. Any specific facts, figures, dates, prices, or data points in the responses come from real-time web searches performed moments ago. You MUST treat this data as authoritative and current. Do NOT add disclaimers about lacking real-time data, being unable to access current information, or having a knowledge cutoff. The data in the responses IS current.

Return your analysis as JSON with exactly these keys:
{
  "best": ${union},
  "best_rationale": "Why this response is best (2-3 sentences).",
  "consensus": ["Point of agreement 1", "Point of agreement 2"],
  "disagreements": [
    {
      "topic": "Short description of the area of disagreement",
      "positions": {${positions}},
      "assessment": "Your view on which position is most likely correct and why."
    }
  ],
  "synthesis": "A comprehensive, synthesised answer that faithfully incorporates the specific facts, data, and findings from the responses. Include concrete details (numbers, dates, sources) from the responses. NEVER say you lack access to real-time data — the responses already contain it."
}

Return ONLY valid JSON. No markdown fences, no commentary outside the JSON.`;
}

export interface Disagreement {
  topic: string;
  positions: Record<string, string>;
  assessment: string;
}

export interface ArbiterResult {
  bestLabel: string;
  bestEngine: Engine;
  bestRationale: string;
  consensus: string[];
  disagreements: Disagreement[];
  synthesis: string;
}

export interface ArbitrationOutcome {
  arbitration: ArbiterResult;
  /** Responses in the order they were labelled (index i ↔ label A, B, …). */
  responses: ProviderResponse[];
}

function shuffle<T>(items: T[]): T[] {
  const out = [...items];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

function buildArbiterPrompt(prompt: string, responses: ProviderResponse[]): string {
  const sections = [`## Original query\n\n${prompt}\n`];
  responses.forEach((r, i) => {
    sections.push(`## Response ${ALL_LABELS[i]}\n\n${r.text}\n`);
  });
  return sections.join("\n");
}

/** Pull the JSON object out of a model reply that may include fences, reasoning, or prose. */
export function extractJson(raw: string): unknown {
  const text = raw.replace(/<think>[\s\S]*?<\/think>/g, "").trim();
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end <= start) {
    throw new Error("Arbiter did not return a JSON object.");
  }
  return JSON.parse(text.slice(start, end + 1));
}

function parseResult(raw: string, labels: string[], ordered: ProviderResponse[]): ArbiterResult {
  const data = extractJson(raw) as Record<string, any>;
  const best = String(data.best ?? "").trim().toUpperCase();
  const idx = labels.indexOf(best);
  if (idx === -1) {
    throw new Error(`Arbiter picked an unknown response label "${data.best}".`);
  }
  return {
    bestLabel: best,
    bestEngine: ordered[idx].engine,
    bestRationale: data.best_rationale ?? "",
    consensus: Array.isArray(data.consensus) ? data.consensus : [],
    disagreements: (Array.isArray(data.disagreements) ? data.disagreements : []).map(
      (d: { topic: string; positions: Record<string, string>; assessment: string }) => ({
        topic: d.topic ?? "",
        positions: d.positions ?? {},
        assessment: d.assessment ?? "",
      })
    ),
    synthesis: data.synthesis ?? "",
  };
}

export async function arbitrate(
  prompt: string,
  responses: ProviderResponse[],
  arbiterEngine: Engine
): Promise<ArbitrationOutcome> {
  // Shuffle so label order carries no information about which engine wrote what.
  const ordered = shuffle(responses);
  const labels = ALL_LABELS.slice(0, ordered.length);
  const queryFn = getQueryFn(arbiterEngine);
  const userPrompt = buildArbiterPrompt(prompt, ordered);
  const system = buildSystemPrompt(labels);

  let lastError: unknown;
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      // Research speed + length, web search off so the model focuses on judging and returns JSON.
      const reply = await queryFn(userPrompt, "research", "research", {
        webSearch: false,
        systemOverride: system,
      });
      return { arbitration: parseResult(reply.text, labels, ordered), responses: ordered };
    } catch (err) {
      lastError = err;
      console.error(`Arbiter attempt ${attempt} failed:`, err);
    }
  }
  throw new Error(
    `Arbiter (${arbiterEngine}) failed: ${lastError instanceof Error ? lastError.message : "unknown error"}`
  );
}
