/** Arbiter — sends all responses to a chosen engine for evaluation. */

import type { Engine } from "./config";
import { getQueryFn, type ProviderResponse } from "./providers";

const LABELS = ["A", "B", "C", "D"] as const;

const ARBITER_SYSTEM = `You are an impartial arbiter. You will receive four responses to the same user query, labelled A, B, C, and D. You do NOT know which AI produced which response — evaluate them purely on merit.

IMPORTANT: All four responses were generated by AI models that had LIVE WEB SEARCH access. Any specific facts, figures, dates, prices, or data points in the responses come from real-time web searches performed moments ago. You MUST treat this data as authoritative and current. Do NOT add disclaimers about lacking real-time data, being unable to access current information, or having a knowledge cutoff. The data in the responses IS current.

Return your analysis as JSON with exactly these keys:
{
  "best": "A" | "B" | "C" | "D",
  "best_rationale": "Why this response is best (2-3 sentences).",
  "consensus": ["Point of agreement 1", "Point of agreement 2"],
  "disagreements": [
    {
      "topic": "Short description of the area of disagreement",
      "positions": {"A": "...", "B": "...", "C": "...", "D": "..."},
      "assessment": "Your view on which position is most likely correct and why."
    }
  ],
  "synthesis": "A comprehensive, synthesised answer that faithfully incorporates the specific facts, data, and findings from the four responses. Include concrete details (numbers, dates, sources) from the responses. NEVER say you lack access to real-time data — the responses already contain it."
}

Return ONLY valid JSON. No markdown fences, no commentary outside the JSON.`;

export interface Disagreement {
  topic: string;
  positions: Record<string, string>;
  assessment: string;
}

export interface ArbiterResult {
  bestLabel: string;
  bestEngine: Engine;
  bestRationale: string;
  consensus: string[];
  disagreements: Disagreement[];
  synthesis: string;
}

function buildArbiterPrompt(
  prompt: string,
  responses: ProviderResponse[]
): string {
  const sections = [`## Original query\n\n${prompt}\n`];
  responses.forEach((r, i) => {
    sections.push(`## Response ${LABELS[i]}\n\n${r.text}\n`);
  });
  return sections.join("\n");
}

export async function arbitrate(
  prompt: string,
  responses: ProviderResponse[],
  arbiterEngine: Engine
): Promise<ArbiterResult> {
  const queryFn = getQueryFn(arbiterEngine);
  const userPrompt = buildArbiterPrompt(prompt, responses);

  // Arbiter always runs at research speed + research length, with web search
  // disabled so the model focuses on evaluating the provided responses and
  // returns strict JSON.  We pass ARBITER_SYSTEM as systemOverride so it
  // becomes the actual system instruction rather than being mixed into the
  // user message (which could be ignored or deprioritised by the model).
  const arbiterResponse = await queryFn(userPrompt, "research", "research", {
    webSearch: false,
    systemOverride: ARBITER_SYSTEM,
  });

  // Parse JSON from the response — strip markdown fences if present.
  let jsonText = arbiterResponse.text.trim();
  if (jsonText.startsWith("```")) {
    jsonText = jsonText.replace(/^```(?:json)?\n?/, "").replace(/\n?```$/, "");
  }
  const data = JSON.parse(jsonText);

  // Map winning label back to the actual engine.
  const labelToEngine: Record<string, Engine> = {};
  LABELS.forEach((label, i) => {
    labelToEngine[label] = responses[i].engine;
  });

  return {
    bestLabel: data.best,
    bestEngine: labelToEngine[data.best],
    bestRationale: data.best_rationale ?? "",
    consensus: data.consensus ?? [],
    disagreements: (data.disagreements ?? []).map(
      (d: { topic: string; positions: Record<string, string>; assessment: string }) => ({
        topic: d.topic,
        positions: d.positions,
        assessment: d.assessment,
      })
    ),
    synthesis: data.synthesis ?? "",
  };
}
